hew more closely to how kani sets git log var

diff --git a/.github/workflows/update-library-subtree.yml b/.github/workflows/update-library-subtree.yml
--- a/.github/workflows/update-library-subtree.yml
+++ b/.github/workflows/update-library-subtree.yml
@@ -5,6 +5,12 @@ on:
     - cron: '0 14 * * *'  # Run at 14:00 UTC every day
   workflow_dispatch:
 
+permissions:
+  checks: write
+  contents: write
+  issues: write
+  pull-requests: write
+
 defaults:
   run:
     shell: bash
@@ -40,29 +46,39 @@ jobs:
         repository: newren/git-filter-repo
         path: git-filter-repo
 
-    - name: Fetch Kani toolchain version
+    - name: Fetch toolchain versions
       run: |
-        cd kani-tmp
-        TOOLCHAIN_DATE=$(grep -oP 'channel = "nightly-\K\d{4}-\d{2}-\d{2}' rust-toolchain.toml)
-        COMMIT_HASH=$(curl https://static.rust-lang.org/dist/$TOOLCHAIN_DATE/channel-rust-nightly-git-commit-hash.txt)
-        if [ -z "$COMMIT_HASH" ]; then
+        CURRENT_TOOLCHAIN_DATE=$(grep -oP 'channel = "nightly-\K\d{4}-\d{2}-\d{2}' verify-rust-std/rust-toolchain.toml)
+        NEXT_TOOLCHAIN_DATE=$(grep -oP 'channel = "nightly-\K\d{4}-\d{2}-\d{2}' kani-tmp/rust-toolchain.toml)
+        CURRENT_COMMIT_HASH=$(curl https://static.rust-lang.org/dist/$CURRENT_TOOLCHAIN_DATE/channel-rust-nightly-git-commit-hash.txt)
+        NEXT_COMMIT_HASH=$(curl https://static.rust-lang.org/dist/$NEXT_TOOLCHAIN_DATE/channel-rust-nightly-git-commit-hash.txt)
+        if [ -z "$NEXT_COMMIT_HASH" ]; then
           echo "Could not find commit hash on static.rust-lang.org"
           exit 1
         fi
-        echo "Kani toolchain date: ${TOOLCHAIN_DATE}"
-        echo "TOOLCHAIN_DATE=${TOOLCHAIN_DATE}" >> $GITHUB_ENV
-        echo "Kani toolchain hash: ${COMMIT_HASH}"
-        echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
+        echo "CURRENT_TOOLCHAIN_DATE=${CURRENT_TOOLCHAIN_DATE}" >> $GITHUB_ENV
+        echo "NEXT_TOOLCHAIN_DATE=${NEXT_TOOLCHAIN_DATE}" >> $GITHUB_ENV
+        echo "CURRENT_COMMIT_HASH=${CURRENT_COMMIT_HASH}" >> $GITHUB_ENV
+        echo "NEXT_COMMIT_HASH=${NEXT_COMMIT_HASH}" >> $GITHUB_ENV
+
+    - name: Get commit log
+      run: |
+        cd rust-tmp
+        git fetch --all
+        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
+        echo "GIT_LOG<<$EOF" >> $GITHUB_ENV
+        git log --oneline ${{ env.CURRENT_COMMIT_HASH }}..${{ env.NEXT_COMMIT_HASH }} | \
+          sed 's#^#https://github.com/rust-lang/rust/commit/#' >> $GITHUB_ENV
+        echo "$EOF" >> $GITHUB_ENV
 
     - name: Update subtree/library locally
       run: |
         cd rust-tmp
-        # Ensure "upstream/master" branch contains the target commit
-        if ! git show ${COMMIT_HASH} --oneline --no-patch; then
-          echo "Rust commit ${COMMIT_HASH} cannot be found."
+        if ! git show ${NEXT_COMMIT_HASH} --oneline --no-patch; then
+          echo "Rust commit ${NEXT_COMMIT_HASH} cannot be found."
           exit 1
         fi
-        git checkout ${COMMIT_HASH}
+        git checkout ${NEXT_COMMIT_HASH}
         ../git-filter-repo/git-filter-repo --subdirectory-filter library --force
         git checkout -b subtree/library
         cd ../verify-rust-std
@@ -80,10 +96,6 @@ jobs:
           git -c user.name=gitbot -c user.email=git@bot rebase
           echo "MERGE_CONFLICTS=maybe" >> $GITHUB_ENV
         fi
-        # Get the commit log
-        git log ${UPSTREAM_FROM}..${UPSTREAM_HEAD} --oneline
-        echo "UPSTREAM_FROM=${UPSTREAM_FROM}" >> $GITHUB_ENV
-        echo "UPSTREAM_HEAD=${UPSTREAM_HEAD}" >> $GITHUB_ENV
 
     - name: Create Pull Request
       if: ${{ env.MERGE_CONFLICTS != 'noop' }}
@@ -92,10 +104,11 @@ jobs:
         title: 'Update subtree/library'
         body: |
           This is an automated PR to update the subtree/library branch to the changes
-          from ${{ env.UPSTREAM_FROM }} to ${{ env.UPSTREAM_HEAD }} of ${{ env.TOOLCHAIN_DATE }}.
+          from ${{ env.CURRENT_TOOLCHAIN_DATE }} (${{ env.CURRENT_COMMIT_HASH }})
+          to ${{ env.NEXT_TOOLCHAIN_DATE }} (${{ env.NEXT_COMMIT_HASH }}).
 
-          Commit range:
-           ${{ env.git_log }}
+          Commit log:
+          ${{ env.GIT_LOG }}
         branch: update-subtree/library
         delete-branch: true
         base: subtree/library
@@ -106,18 +119,17 @@ jobs:
       run: |
         cd verify-rust-std
         git checkout main
-        # This command may fail, which will require human intervention.
         if ! git \
             -c user.name=gitbot -c user.email=git@bot \
             subtree merge --prefix=library update-subtree/library --squash; then
           echo "MERGE_CONFLICTS=yes" >> $GITHUB_ENV
-          git -c user.name=gitbot -c user.email=git@bot commit -a -m "Merge from $COMMIT_HASH with conflicts"
+          git -c user.name=gitbot -c user.email=git@bot commit -a -m "Merge from $NEXT_COMMIT_HASH with conflicts"
         else
           echo "MERGE_CONFLICTS=no" >> $GITHUB_ENV
         fi
-        sed -i "s/^channel = \"nightly-.*\"/channel = \"${TOOLCHAIN_DATE}\"/" rust-toolchain.toml
+        sed -i "s/^channel = \"nightly-.*\"/channel = \"nightly-${NEXT_TOOLCHAIN_DATE}\"/" rust-toolchain.toml
         git -c user.name=gitbot -c user.email=git@bot \
-          commit -m "Update toolchain to ${TOOLCHAIN_DATE}" rust-toolchain.toml
+          commit -m "Update toolchain to nightly-${NEXT_TOOLCHAIN_DATE}" rust-toolchain.toml
 
     - name: Create Pull Request without conflicts
       if: ${{ env.MERGE_CONFLICTS == 'no' }}
@@ -126,12 +138,13 @@ jobs:
         title: 'Merge subtree update'
         body: |
           This is an automated PR to merge library subtree updates
-          from ${{ env.UPSTREAM_FROM }} to ${{ env.UPSTREAM_HEAD }} of ${{ env.TOOLCHAIN_DATE }}
+          from ${{ env.CURRENT_TOOLCHAIN_DATE }} (${{ env.CURRENT_COMMIT_HASH }})
+          to ${{ env.NEXT_TOOLCHAIN_DATE }} (${{ env.NEXT_COMMIT_HASH }})
           into main. This is a clean merge, no conflicts were detected.
 
-          Commit range:
-           ${{ env.git_log }}
-        branch: sync-${{ env.TOOLCHAIN_DATE }}
+          Commit log:
+          ${{ env.GIT_LOG }}
+        branch: sync-${{ env.NEXT_TOOLCHAIN_DATE }}
         delete-branch: true
         base: main
         path: verify-rust-std
@@ -143,13 +156,14 @@ jobs:
         title: 'Merge subtree update'
         body: |
           This is an automated PR to merge library subtree updates
-          from ${{ env.UPSTREAM_FROM }} to ${{ env.UPSTREAM_HEAD }} of ${{ env.TOOLCHAIN_DATE }}
+          from ${{ env.CURRENT_TOOLCHAIN_DATE }} (${{ env.CURRENT_COMMIT_HASH }})
+          to ${{ env.NEXT_TOOLCHAIN_DATE }} (${{ env.NEXT_COMMIT_HASH }})
           into main. `git merge` resulted in conflicts, which require manual resolution.
-          Files were committed with merge conflict markers.
+          Files were commited with merge conflict markers.
 
-          Commit range:
-            ${{ env.git_log }}
-        branch: sync-${{ env.TOOLCHAIN_DATE }}
+          Commit log:
+          ${{ env.GIT_LOG }}
+        branch: sync-${{ env.NEXT_TOOLCHAIN_DATE }}
         delete-branch: true
         base: main
         path: verify-rust-std
